### ISSUE TITLE
Environment variable

### ISSUE THREAD

**Issue by bdorminy** [obrigg/meraki-channel-distribution#3]
I am not a Python expert. How do I add the API Key as an environment variable for Python running on a Windows server? I added it to the Windows environment variables but I am still getting an error.

**Comment by obrigg** [comment]
Oh.. I think I know what the problem might be.
This repo is 3 years old, I think the name of the environment variable the Meraki Python SDK is using has changed at some point.

Try using the variable 'MERAKI_DASHBOARD_API_KEY' please.

**Comment by bdorminy** [comment]
That's what it was. Thanks!

**Comment by obrigg** [comment]
Thanks for confirming. I'll update the README.
